### PR TITLE
redis 7.2

### PR DESCRIPTION
**Pull request by coreypurcell**
fixes the testing of the cli options

#41

### CODE REVIEW

**Review by edmorley — APPROVED** [review]
Thank you for the follow-up!

**Comment by edmorley** [comment]
@coreypurcell Let us know when you would like a new buildpack release :-)

**Comment by coreypurcell** [comment]
I think we release it @edmorley 7.2 has been GA for a while.

**Comment by edmorley** [comment]
Sure - happy to!

Published:

```
$ heroku buildpacks:publish heroku/ci-redis master
Publishing buildpack heroku/ci-redis... done
Publishing buildpack was successful

$ h buildpacks:versions heroku/ci-redis | head -n 4
 Version Released At              Status
 ─────── ──────────────────────── ─────────
 13      2024-09-25T15:37:43.806Z published
 12      2024-05-22T14:24:20.213Z published
```

**Pull request merged**
